### ISSUE TITLE
How to get the prebuild stage4

### ISSUE THREAD

**Issue by DraGiuS** [lucascouts/bentoo#1]
This project seems very interesting, but where is the stage4 ?
Thanks.

**Comment by lucascouts** [comment]
hi, here is the personal overlay with update and extra packages, the stage4 file will be available on site the next week.

**Comment by lucascouts** [comment]
The binaries packages is here : http://binhost.bentoo.info

and is almost done too.

**Comment by DraGiuS** [comment]
I dont know,  it will be installable with calamares ?

**Comment by lucascouts** [comment]
"I dont know" ?

not at first, but later, for now will be in tar.xz as the regular stage3.

**Comment by lucascouts** [comment]
The site is online, but the stages will be available only Sunday.

https://bentoo.info/
